classDiagram
direction TB
    class Menu {
        Items
        price
        offers
    }

    class Order {
        tracking_number
        status
	sub_total()
    	grouping_Items()
        changeStatus()
        create_order()
        Notify_user()
    }

    class Restaurant {
        resturant_name
        receive_order()
        confirmed_order()
        update_order_status()
    }

    class user {
        phone_number
        address
        email
        password
        name
        track_oreder()
        selectItem()
        send_order()
    }

   user "1" --> "*" Order : places
Restaurant "1" --> "*" Order : accepting 
Restaurant "1" -- "*" Menu 
user "1" --> "*" Restaurant : viewing
Order "0.." --> "1.." Menu : contains
